# DocToc is a tool that automatically generates Table of Contents for
# Markdown files. It can be installed like any other NPM module:
#
#    npm install -g doctoc

update-table-of-contents: README.md
	doctoc --github --notitle $<
